apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imageupdater
  namespace: argocd
  annotations:
    # ✅ Semver with constraint
    argocd-image-updater.argoproj.io/image-list: imageupdater=ghcr.io/abhishekg2244/argocd:^3.0

    # ✅ Git write-back
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds

    # ✅ Semver strategy
    argocd-image-updater.argoproj.io/imageupdater.update-strategy: semver

spec:
  project: default
  source:
    repoURL: https://github.com/abhishekg2244/my-app-manifests.git
    targetRevision: feature/m1
    path: imageUpdater/manifests   # 👈 IMPORTANT (root where kustomization.yaml exists)
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true