apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
            namespace: default
            name: nginx2-app
            path: nginx
          
          - cluster: https://kubernetes.default.svc
            namespace: default
            name: todo2-app
            path: todo

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/abhishekg2244/my-app-manifests.git
        targetRevision: feature/m1
        path: '{{path}}'
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
            - CreateNamespace=true